// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 应用生命周期相关：窗口显示控制。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Ready 由前端在挂载完成、首帧渲染后调用，此时才显示窗口，避免启动白屏。
 * 重复调用与多次调用均安全。
 * @returns {$CancellablePromise<void>}
 */
export function Ready() {
    return $Call.ByID(3541727230);
}

/**
 * SetShowFunc 后置注入窗口显示函数（窗口在 application.New 之后才能创建）。
 * @param {any} f
 * @returns {$CancellablePromise<void>}
 */
export function SetShowFunc(f) {
    return $Call.ByID(555365962, f);
}

/**
 * Watchdog 兜底：前端异常（如脚本错误导致 Ready 未被调用）时，
 * 超时后强制显示窗口，避免用户面对不可见的应用。
 * @param {time$0.Duration} d
 * @returns {$CancellablePromise<void>}
 */
export function Watchdog(d) {
    return $Call.ByID(1946664516, d);
}
