// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DocumentService 页面编辑：打开、增删页、插入 PDF 页面、另存。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbsorbBufferAux 只合并缓冲区的辅助数据（书签/页标签/附件，页码平移），不改页面结构。
 * 纯前端页面流：页面顺序由前端 pageSeq 维护，仅在保存时装配。
 * @param {string} id
 * @param {number} atIndex
 * @param {boolean} before
 * @returns {$CancellablePromise<$models.PlaceResult | null>}
 */
export function AbsorbBufferAux(id, atIndex, before) {
    return $Call.ByID(2605318782, id, atIndex, before).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Close 关闭文档会话并清理临时数据。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Close(id) {
    return $Call.ByID(2365882973, id);
}

/**
 * @param {string} id
 * @param {string} pages
 * @returns {$CancellablePromise<$models.DocInfo | null>}
 */
export function DeletePages(id, pages) {
    return $Call.ByID(4229108756, id, pages).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DiscardBuffer 丢弃挂起的导入内容。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DiscardBuffer(id) {
    return $Call.ByID(2117883089, id);
}

/**
 * EnsurePageThumb 确保第 page 页的 180px 缩略图存在，缺失则同步渲染（自愈）。
 * @param {string} id
 * @param {number} page
 * @returns {$CancellablePromise<void>}
 */
export function EnsurePageThumb(id, page) {
    return $Call.ByID(1870931582, id, page);
}

/**
 * GenerateThumbnails 异步生成缩略图（fromPage 之前的页保留缓存，增量重渲染）；
 * 完成事件 result 为静态资源前缀 "/thumbs/<id>"。
 * @param {string} id
 * @param {number} width
 * @param {number} fromPage
 * @returns {$CancellablePromise<string>}
 */
export function GenerateThumbnails(id, width, fromPage) {
    return $Call.ByID(2221362589, id, width, fromPage);
}

/**
 * HealResource 渲染资源 uuid 的 <width>px 图（静态服务缺失时自愈）。
 * @param {string} uuid
 * @param {number} width
 * @returns {$CancellablePromise<void>}
 */
export function HealResource(uuid, width) {
    return $Call.ByID(448711061, uuid, width);
}

/**
 * Import 批量导入 PDF/图片到挂起缓冲区（异步任务）。
 * 完成事件 result 为 {bufferID, pageCount}；缓冲区缩略图位于 /imgs/<bufferID>/pN.png。
 * 同一文档同时只保留一个缓冲区，新导入会覆盖旧缓冲区。
 * @param {string} id
 * @param {$models.ImportRequest} req
 * @returns {$CancellablePromise<string>}
 */
export function Import(id, req) {
    return $Call.ByID(2983142022, id, req);
}

/**
 * Info 查询文档状态。
 * @param {string} id
 * @returns {$CancellablePromise<$models.DocInfo | null>}
 */
export function Info(id) {
    return $Call.ByID(2421780355, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * InsertBlankPages 在 atIndex 页前/后插入 count 张空白页（尺寸匹配锚点页）。
 * 缩略图：生成灰色占位 PNG，零重渲染。
 * @param {string} id
 * @param {number} atIndex
 * @param {number} count
 * @param {boolean} before
 * @returns {$CancellablePromise<$models.DocInfo | null>}
 */
export function InsertBlankPages(id, atIndex, count, before) {
    return $Call.ByID(3531105772, id, atIndex, count, before).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * PageThumbnail 同步渲染第 pageNr 页（1-based）缩略图，返回可访问 URL。
 * 宽度上限 600px；已存在同名缓存时直接返回。用于封面与其他面板的页面预览。
 * InsertImagePage 把一张图片作为一页插入文档：页面尺寸继承锚点页，
 * 图片等比缩放完整放入。atIndex 1-based；before=true 插在 atIndex 之前。
 * MovePages 将选中页按原顺序移动到 atIndex 位置（1-based，基于移动前编号）。
 * before=true 表示放在原第 atIndex 页之前，false 为之后。
 * @param {string} id
 * @param {string} pages
 * @param {number} atIndex
 * @param {boolean} before
 * @returns {$CancellablePromise<$models.DocInfo | null>}
 */
export function MovePages(id, pages, atIndex, before) {
    return $Call.ByID(3652352738, id, pages, atIndex, before).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Open 打开 PDF 并注册会话。
 * @param {string} path
 * @returns {$CancellablePromise<$models.DocInfo | null>}
 */
export function Open(path) {
    return $Call.ByID(3566915499, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * PageResources 返回文档全部页面的资源 uuid 序列（首次调用会渲染全部页面的基图）。
 * 同时刷新 doc.res：该序列即页面逻辑顺序，前端据此拼装缩略图/预览地址。
 * @param {string} id
 * @returns {$CancellablePromise<string[]>}
 */
export function PageResources(id) {
    return $Call.ByID(459537273, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * InsertBlankPages 在 pageIndex 页前/后插入 count 张空白页。
 * 空白页尺寸自动匹配锚点页（1-based；pageIndex 可为 PageCount+1 追加到末尾）。
 * DeletePages 删除页面选择表达式指定的页（如 "2,5-7"）。
 * PageThumbnail 同步渲染单页大图（用于预览浮层），返回可访问 URL。
 * 缓存于 <thumbs>/big-p<N>.png；文件随重排被清理后在下次请求时重渲染。
 * @param {string} id
 * @param {number} pageNr
 * @param {number} width
 * @returns {$CancellablePromise<string>}
 */
export function PageThumbnail(id, pageNr, width) {
    return $Call.ByID(1415534424, id, pageNr, width);
}

/**
 * PlaceBuffer 把挂起的导入内容整体插入到 atIndex 位置（1-based），
 * 并把导入 PDF 的书签/页标签/附件合并进当前会话（页码自动平移）。
 * @param {string} id
 * @param {number} atIndex
 * @param {boolean} before
 * @returns {$CancellablePromise<$models.PlaceResult | null>}
 */
export function PlaceBuffer(id, atIndex, before) {
    return $Call.ByID(2493071616, id, atIndex, before).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Save 保存到原始文件（合并辅助数据；临时文件 + 原子替换，避免写坏原文件）。
 * 
 * 顺序：mergeAux → adoptWorkCopy → atomicWrite。
 * 先接纳新工作版本再写原文件，保证即便写原文件失败，会话状态也自洽：
 * WorkPath 反映合并后的内容，下次保存不会基于旧内容重新装配。
 * @param {string} id
 * @param {$models.SaveOptions | null} opts
 * @returns {$CancellablePromise<$models.DocInfo | null>}
 */
export function Save(id, opts) {
    return $Call.ByID(369543186, id, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SaveAs 另存为新文件：合并辅助数据后写临时文件原子替换，
 * 并把会话切换到目标文件（后续 Save 写回目标；docInfo 返回新路径与文件名）。
 * 
 * 顺序与 Save 一致：mergeAux → adoptWorkCopy → atomicWrite(target)。
 * 先接纳新工作版本再写目标文件，失败时目标文件保持不变，
 * 会话 WorkPath 已自洽，用户可重试。
 * @param {string} id
 * @param {string} targetPath
 * @param {$models.SaveOptions | null} opts
 * @returns {$CancellablePromise<$models.DocInfo | null>}
 */
export function SaveAs(id, targetPath, opts) {
    return $Call.ByID(1474692398, id, targetPath, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.PlaceResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.DocInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($Create.Any);
