// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImageService 多图片合并为 PDF。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Prepare 把选中的图片复制进工作区会话目录并返回可预览的条目列表。
 * 顺序即列表顺序；前端可自行调整顺序后作为 Start 的 ImagePaths。
 * @param {string[]} imagePaths
 * @returns {$CancellablePromise<$models.ImageItem[]>}
 */
export function Prepare(imagePaths) {
    return $Call.ByID(1119516368, imagePaths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Start 异步执行图片转 PDF；完成事件 result 为输出文件路径。
 * @param {$models.ImagesToPDFRequest} req
 * @returns {$CancellablePromise<string>}
 */
export function Start(req) {
    return $Call.ByID(329111507, req);
}

// Private type creation functions
const $$createType0 = $models.ImageItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
