// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MergeService 多 PDF 合并。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Start 异步执行合并；完成事件 result 为输出文件路径。
 * @param {$models.MergeRequest} req
 * @returns {$CancellablePromise<string>}
 */
export function Start(req) {
    return $Call.ByID(1628210388, req);
}
