// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MetaService 元数据：页标签、附件会话。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddDocAttachments 添加附件（复制到工作区暂存，保存时写入 PDF）。
 * @param {string} id
 * @param {string[]} paths
 * @returns {$CancellablePromise<$models.AttachmentInfo[]>}
 */
export function AddDocAttachments(id, paths) {
    return $Call.ByID(3602172762, id, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ClearDocAttachments 清空附件会话（移除全部原文档附件 + 全部新增）。
 * @param {string} id
 * @returns {$CancellablePromise<$models.AttachmentInfo[]>}
 */
export function ClearDocAttachments(id) {
    return $Call.ByID(3038849580, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListAttachments 列出附件。
 * @param {string} path
 * @returns {$CancellablePromise<$models.AttachmentInfo[]>}
 */
export function ListAttachments(path) {
    return $Call.ByID(2443970167, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListDocAttachments 列出附件会话：原文档附件（减去移除集合）+ 新增附件。
 * @param {string} id
 * @returns {$CancellablePromise<$models.AttachmentInfo[]>}
 */
export function ListDocAttachments(id) {
    return $Call.ByID(2638160163, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ReadPageLabels 读取页标签。
 * @param {string} path
 * @returns {$CancellablePromise<$models.PageLabel[]>}
 */
export function ReadPageLabels(path) {
    return $Call.ByID(4050887715, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RemoveDocAttachments 移除附件并返回最新列表。
 * @param {string} id
 * @param {string[]} names
 * @returns {$CancellablePromise<$models.AttachmentInfo[]>}
 */
export function RemoveDocAttachments(id, names) {
    return $Call.ByID(3249233415, id, names).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AttachmentInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PageLabel.createFrom;
const $$createType3 = $Create.Array($$createType2);
