// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AttachmentInfo 附件信息。
 */
export class AttachmentInfo {
    /**
     * Creates a new AttachmentInfo instance.
     * @param {Partial<AttachmentInfo>} [$$source = {}] - The source object to create the AttachmentInfo.
     */
    constructor($$source = {}) {
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Date | null | undefined}
             */
            this["modTime"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AttachmentInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AttachmentInfo}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("modTime" in $$parsedSource) {
            $$parsedSource["modTime"] = $$createField2_0($$parsedSource["modTime"]);
        }
        return new AttachmentInfo(/** @type {Partial<AttachmentInfo>} */($$parsedSource));
    }
}

/**
 * DocInfo 对前端暴露的文档信息。
 */
export class DocInfo {
    /**
     * Creates a new DocInfo instance.
     * @param {Partial<DocInfo>} [$$source = {}] - The source object to create the DocInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("sourcePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourcePath"] = "";
        }
        if (!("fileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileName"] = "";
        }
        if (!("pageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pageCount"] = 0;
        }
        if (!("pages" in $$source)) {
            /**
             * @member
             * @type {PageDim[]}
             */
            this["pages"] = [];
        }
        if (!("hasThumbs" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasThumbs"] = false;
        }
        if (!("docVer" in $$source)) {
            /**
             * DocVer 文档修订号：任何改变页面内容的操作后递增，前端用于整体缓存失效
             * @member
             * @type {number}
             */
            this["docVer"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * PageRes 页面内容资源 uuid 序列（内容寻址，前端据此拼装缩略图/预览地址）
             * @member
             * @type {string[] | undefined}
             */
            this["pageRes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocInfo}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        const $$createField7_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pages" in $$parsedSource) {
            $$parsedSource["pages"] = $$createField4_0($$parsedSource["pages"]);
        }
        if ("pageRes" in $$parsedSource) {
            $$parsedSource["pageRes"] = $$createField7_0($$parsedSource["pageRes"]);
        }
        return new DocInfo(/** @type {Partial<DocInfo>} */($$parsedSource));
    }
}

/**
 * ImageItem 图片会话中的单个条目；URL 供前端 <img> 预览。
 */
export class ImageItem {
    /**
     * Creates a new ImageItem instance.
     * @param {Partial<ImageItem>} [$$source = {}] - The source object to create the ImageItem.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImageItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageItem(/** @type {Partial<ImageItem>} */($$parsedSource));
    }
}

/**
 * ImagesToPDFRequest 图片导入请求。
 */
export class ImagesToPDFRequest {
    /**
     * Creates a new ImagesToPDFRequest instance.
     * @param {Partial<ImagesToPDFRequest>} [$$source = {}] - The source object to create the ImagesToPDFRequest.
     */
    constructor($$source = {}) {
        if (!("imagePaths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["imagePaths"] = [];
        }
        if (!("outputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputPath"] = "";
        }
        if (!("pageSize" in $$source)) {
            /**
             * A4 / A3 / Letter / Auto
             * @member
             * @type {string}
             */
            this["pageSize"] = "";
        }
        if (!("landscape" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["landscape"] = false;
        }
        if (!("marginPt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["marginPt"] = 0;
        }
        if (!("sortMode" in $$source)) {
            /**
             * given | natural
             * @member
             * @type {string}
             */
            this["sortMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImagesToPDFRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImagesToPDFRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("imagePaths" in $$parsedSource) {
            $$parsedSource["imagePaths"] = $$createField0_0($$parsedSource["imagePaths"]);
        }
        return new ImagesToPDFRequest(/** @type {Partial<ImagesToPDFRequest>} */($$parsedSource));
    }
}

/**
 * ImportRequest 批量导入请求：混合 PDF 与图片，按给定顺序合成待放置内容。
 */
export class ImportRequest {
    /**
     * Creates a new ImportRequest instance.
     * @param {Partial<ImportRequest>} [$$source = {}] - The source object to create the ImportRequest.
     */
    constructor($$source = {}) {
        if (!("paths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["paths"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField0_0($$parsedSource["paths"]);
        }
        return new ImportRequest(/** @type {Partial<ImportRequest>} */($$parsedSource));
    }
}

/**
 * MergeRequest 合并请求。
 */
export class MergeRequest {
    /**
     * Creates a new MergeRequest instance.
     * @param {Partial<MergeRequest>} [$$source = {}] - The source object to create the MergeRequest.
     */
    constructor($$source = {}) {
        if (!("inputPaths" in $$source)) {
            /**
             * 已排序的输入文件
             * @member
             * @type {string[]}
             */
            this["inputPaths"] = [];
        }
        if (!("outputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputPath"] = "";
        }
        if (!("sortMode" in $$source)) {
            /**
             * "given" 按列表顺序 | "natural" 按文件名自然序重排
             * @member
             * @type {string}
             */
            this["sortMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeRequest}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inputPaths" in $$parsedSource) {
            $$parsedSource["inputPaths"] = $$createField0_0($$parsedSource["inputPaths"]);
        }
        return new MergeRequest(/** @type {Partial<MergeRequest>} */($$parsedSource));
    }
}

/**
 * OutlineNode 书签树节点。
 */
export class OutlineNode {
    /**
     * Creates a new OutlineNode instance.
     * @param {Partial<OutlineNode>} [$$source = {}] - The source object to create the OutlineNode.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("page" in $$source)) {
            /**
             * 1-based 目标页
             * @member
             * @type {number}
             */
            this["page"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["bold"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["italic"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {OutlineNode[] | undefined}
             */
            this["kids"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutlineNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OutlineNode}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("kids" in $$parsedSource) {
            $$parsedSource["kids"] = $$createField4_0($$parsedSource["kids"]);
        }
        return new OutlineNode(/** @type {Partial<OutlineNode>} */($$parsedSource));
    }
}

/**
 * PageDim 页面尺寸（pt）。
 */
export class PageDim {
    /**
     * Creates a new PageDim instance.
     * @param {Partial<PageDim>} [$$source = {}] - The source object to create the PageDim.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PageDim instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PageDim}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PageDim(/** @type {Partial<PageDim>} */($$parsedSource));
    }
}

/**
 * RemoveAttachments 移除附件并写入 outPath；files 为空表示全部移除。
 * PageLabel 页标签区间（与 PDF number tree 对应）。
 */
export class PageLabel {
    /**
     * Creates a new PageLabel instance.
     * @param {Partial<PageLabel>} [$$source = {}] - The source object to create the PageLabel.
     */
    constructor($$source = {}) {
        if (!("startPage" in $$source)) {
            /**
             * 区间起始页（0-based）
             * @member
             * @type {number}
             */
            this["startPage"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * 前缀文本
             * @member
             * @type {string | undefined}
             */
            this["prefix"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "" | D | R | r | A | a
             * @member
             * @type {string | undefined}
             */
            this["style"] = undefined;
        }
        if (!("startValue" in $$source)) {
            /**
             * 该区间起始编号，默认 1
             * @member
             * @type {number}
             */
            this["startValue"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PageLabel instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PageLabel}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PageLabel(/** @type {Partial<PageLabel>} */($$parsedSource));
    }
}

/**
 * PlaceResult 放置结果：文档信息 + 合并进当前会话的辅助数据（前端据此同步各子页面）。
 */
export class PlaceResult {
    /**
     * Creates a new PlaceResult instance.
     * @param {Partial<PlaceResult>} [$$source = {}] - The source object to create the PlaceResult.
     */
    constructor($$source = {}) {
        if (!("info" in $$source)) {
            /**
             * @member
             * @type {DocInfo | null}
             */
            this["info"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {OutlineNode[] | undefined}
             */
            this["addedOutline"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PageLabel[] | undefined}
             */
            this["addedLabels"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {AttachmentInfo[] | undefined}
             */
            this["addedAttachments"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlaceResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlaceResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType9;
        const $$createField3_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("info" in $$parsedSource) {
            $$parsedSource["info"] = $$createField0_0($$parsedSource["info"]);
        }
        if ("addedOutline" in $$parsedSource) {
            $$parsedSource["addedOutline"] = $$createField1_0($$parsedSource["addedOutline"]);
        }
        if ("addedLabels" in $$parsedSource) {
            $$parsedSource["addedLabels"] = $$createField2_0($$parsedSource["addedLabels"]);
        }
        if ("addedAttachments" in $$parsedSource) {
            $$parsedSource["addedAttachments"] = $$createField3_0($$parsedSource["addedAttachments"]);
        }
        return new PlaceResult(/** @type {Partial<PlaceResult>} */($$parsedSource));
    }
}

/**
 * SaveOptions 保存时的辅助数据合并选项。
 * nil 字段 = 不修改该项；空切片 = 移除该项全部内容。
 */
export class SaveOptions {
    /**
     * Creates a new SaveOptions instance.
     * @param {Partial<SaveOptions>} [$$source = {}] - The source object to create the SaveOptions.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {OutlineNode[] | null | undefined}
             */
            this["outline"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * PageSeq 最终页面序列（内容资源 uuid / blank-<w>x<h> 空白标记）。
             * 前端的删除/移动/插入均为纯前端操作，仅在保存/另存为时提交该序列，由后端装配。
             * @member
             * @type {string[] | null | undefined}
             */
            this["pageSeq"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PageLabel[] | null | undefined}
             */
            this["labels"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SaveOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SaveOptions}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType12;
        const $$createField1_0 = $$createType13;
        const $$createField2_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("outline" in $$parsedSource) {
            $$parsedSource["outline"] = $$createField0_0($$parsedSource["outline"]);
        }
        if ("pageSeq" in $$parsedSource) {
            $$parsedSource["pageSeq"] = $$createField1_0($$parsedSource["pageSeq"]);
        }
        if ("labels" in $$parsedSource) {
            $$parsedSource["labels"] = $$createField2_0($$parsedSource["labels"]);
        }
        return new SaveOptions(/** @type {Partial<SaveOptions>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Nullable($Create.DateFromTime);
const $$createType1 = PageDim.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = OutlineNode.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = DocInfo.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = PageLabel.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = AttachmentInfo.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Nullable($$createType5);
const $$createType13 = $Create.Nullable($$createType3);
const $$createType14 = $Create.Nullable($$createType9);
