// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * OutlineService 书签/目录读取、提取、修改。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ApplyInPlace 将编辑后的书签树写回：输出到新文件（不覆盖原文件由前端/用户决定路径）。
 * @param {string} inPath
 * @param {string} outPath
 * @param {$models.OutlineNode[]} nodes
 * @param {boolean} replace
 * @returns {$CancellablePromise<void>}
 */
export function Apply(inPath, outPath, nodes, replace) {
    return $Call.ByID(1378552602, inPath, outPath, nodes, replace);
}

/**
 * ExportJSON 提取目录结构为 pdfcpu JSON 文件。
 * @param {string} inPath
 * @param {string} outPath
 * @returns {$CancellablePromise<void>}
 */
export function ExportJSON(inPath, outPath) {
    return $Call.ByID(3898920066, inPath, outPath);
}

/**
 * ExportText 导出书签为人类可读的缩进文本（每行一个节点：
 * 前导 \t 表示层级；标题与页码以 \t 分隔），写入 outPath。
 * @param {string} inPath
 * @param {string} outPath
 * @returns {$CancellablePromise<void>}
 */
export function ExportText(inPath, outPath) {
    return $Call.ByID(154054887, inPath, outPath);
}

/**
 * ImportJSON 从 pdfcpu JSON 导入书签。
 * @param {string} inPath
 * @param {string} jsonPath
 * @param {string} outPath
 * @param {boolean} replace
 * @returns {$CancellablePromise<void>}
 */
export function ImportJSON(inPath, jsonPath, outPath, replace) {
    return $Call.ByID(4186431181, inPath, jsonPath, outPath, replace);
}

/**
 * Read 读取文件的书签树。
 * @param {string} path
 * @returns {$CancellablePromise<$models.OutlineNode[]>}
 */
export function Read(path) {
    return $Call.ByID(2776756442, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RemoveAllToFile 移除全部书签并写入 outPath。
 * @param {string} inPath
 * @param {string} outPath
 * @returns {$CancellablePromise<void>}
 */
export function RemoveAllToFile(inPath, outPath) {
    return $Call.ByID(1965089154, inPath, outPath);
}

// Private type creation functions
const $$createType0 = $models.OutlineNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
